apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kyverno-install-v1.12.5.yaml
  - policies

patches:
  - target:
      kind: ConfigMap
      name: kyverno
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: kyverno
        namespace: kyverno
      data:
        webhookAnnotations: "{}"
