backstage:
  postgresql:
    enabled: true

  backstage:
    replicas: 1
    revisionHistoryLimit: 2

    image:
      repository: backstage/backstage
      digest: "sha256:d20016b0455c3d359461be69d85c8b672f0f7ad19d41b773bf4a315ec911ca3c"
      pullPolicy: IfNotPresent

    extraEnvVars:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: neuroscale-backstage-secrets
            key: GITHUB_TOKEN
            optional: true

    appConfig:
      app:
        baseUrl: http://localhost:7010
      backend:
        baseUrl: http://localhost:7010
        auth:
          dangerouslyDisableDefaultAuthPolicy: true
        listen:
          port: 7007
          host: "0.0.0.0"

      integrations:
        github:
          - host: github.com
            token: ${GITHUB_TOKEN}

      catalog:
        locations:
          - type: url
            target: https://github.com/sodiq-code/neuroscale-platform/blob/main/backstage/templates/model-endpoint/template.yaml
            rules:
              - allow: [Template]

      scaffolder:
        defaultCommitMessage: "chore(scaffolder): apply template"

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits: {}

    startupProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 10
      periodSeconds: 10
      failureThreshold: 30
    livenessProbe:
      initialDelaySeconds: 300
      timeoutSeconds: 10
      periodSeconds: 10
      failureThreshold: 10
    readinessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 10
      periodSeconds: 10
      failureThreshold: 10