apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: demo-iris-2
  namespace: default
  labels:
    owner: platform-team
    cost-center: cc-demo
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
