apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-root-containers
spec:
  admission: true
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-runAsNonRoot-on-deployment
      match:
        any:
          - resources:
              kinds:
                - Deployment
              namespaces:
                - default
      skipBackgroundRequests: true
      validate:
        message: "Deployment containers must set securityContext.runAsNonRoot: true."
        pattern:
          spec:
            template:
              spec:
                containers:
                  - securityContext:
                      runAsNonRoot: true
