apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - require-standard-labels-inferenceservice.yaml
  - require-standard-labels-deployment.yaml
  - require-resource-requests-limits.yaml
  - disallow-latest-image-tag.yaml
  - disallow-root-containers.yaml
