apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-standard-labels-deployment
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-owner-and-cost-center-on-deployment
      match:
        any:
          - resources:
              kinds:
                - Deployment
              namespaces:
                - default
      validate:
        message: "Deployment resources must set metadata.labels.owner and metadata.labels.cost-center."
        pattern:
          metadata:
            labels:
              owner: "?*"
              cost-center: "?*"
