apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-standard-labels-inferenceservice
spec:
  admission: true
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-owner-and-cost-center-on-isvc
      match:
        any:
          - resources:
              kinds:
                - InferenceService
              namespaces:
                - default
      skipBackgroundRequests: true
      validate:
        message: "InferenceService resources must set metadata.labels.owner and metadata.labels.cost-center."
        pattern:
          metadata:
            labels:
              owner: "?*"
              cost-center: "?*"
