opencost:
  opencost:
    exporter:
      defaultClusterId: neuroscale-local
      env:
        - name: CLOUD_COST_ENABLED
          value: "false"
    prometheus:
      internal:
        enabled: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
    ui:
      enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 55Mi
        limits:
          cpu: 100m
          memory: 128Mi
    resources:
      requests:
        cpu: 10m
        memory: 55Mi
      limits:
        cpu: 100m
        memory: 128Mi
