apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neuroscale-serving-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sodiq-code/neuroscale-platform.git
    targetRevision: main
    path: infrastructure/serving-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
